language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
addons:
  postgresql: "9.4"

before_script:
  - ( cd spec/dummy; rake db:create RAILS_ENV=test; rake db:migrate RAILS_ENV=test )
